---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tsl-rag-postgres
  namespace: tsl-rag-prod
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCbmhjM85MZG3Kk+9LzX4dMfIfekL8x7ZkL2FBxMhscL/p0cyhFAHdPm0wrTt2Wp/JQfIyeh0iPZc3Pewc1lixnsbIk4dwXpQqR0RDN4/ZxFth3+Tdc95dhvreClNS2vSDU8YK75QdBIqtpH+SN7xJj3x/F+G+kC3kDTjIvE6J/vOHKhm+VOQooKQg76sW8JW9temwG5P2FmRCEuEL7yU2RGAimT0pq8lFrjnT6tMVwd34vBkM0ntJ4J0AQKrvtQ5JRJjmHZWBbesyvKs8N09Aza/P/UIKecCUgTMNoVbwI3NaFNtSSOXKvy5n44sQkLBTZzgKm/oKojtxi3U6k11brM0/elPld+GrWiwDqe6XisS2zUE3vREhISwF7+jUswUHx69HGLgDu00faD1HBpJAjaJpDaaTSO/W9HjOtto4hHD86QVp6DOBZJ/O5P+VtN25s4RN5w7OzKJc0cAzoHwKfnStrGc8EpBL80PlMsBjmHf1p2Ks6Afx2bdamNqybaRJ4w8jCTvCw/PLCPuhGwtomxj7ylj6F/GHWvs+4Z6TfjZFkLwOdP0/3vGWvwbZIvvGofK44YU22PlUgA6QWMndrS2idE66ZkEIwgPvxJOom1OmJKHM9kgTWfeDoRv8Wi6myEkBNzRGH400uPVgKMak8LtlSuqv4FTPBooYoCe1df845w7qu/ni4UOW5yWj1gmwr3S6Netj95p4if1zO32RkyYoi3d/DXxlD/HkHHfl1NHpam2hwkP+pqKsiHc2KK7g=
    POSTGRES_USER: AgCiu4XtQAl1t/WflllgaW2rBiKQi+noTqyRg1JJGH7uyHYfZM3aEtiHIHMwWhESkLPMChFAEfS1Cl+tXFDE2wOPL4CYJe/y9A5/NUcUkhXPJDIlfkpUg/lIloK+qZzANLJRjoPuS+3a1BBYj102Iw/CO8QH40HsbzDQXxyr/53oA41uYxZhH8kCq5Hx/JvxCL4UVKR9XUd5TxUFw8WObhnWpUGA+VgfQhxNgS7a0fCwgrOHXjALm3XFGbYZxjty039GrB2M2nkBPDuubVSlWBhImOn60JBrfJ1HHp0G7cfnSpoGBK9pnzl2W2KazZxJhEdR9GkA/IxM0Hd3Xk08Cg8ekCnIF2zqQlHfGaG1vvmMmrUIMQ3/k5IR+OhQq0y9nWHYsAp3aDJYsdd6P65Vb2W4GTO4CRAGwYufQS30iYBW1mxZfJD/rMDF3jEs2NyG2gxZAi+eIZzJOsq5qI4oUcwOLngwq3+ruc4s/dWsyPlpX6/GMRRB7frhCpKLDQa3Zq2gNPFRI8+qD8WMTrRe4zlXZ+4mjo8Pi1iTBmOqswzgPUFCkRhJ2m1lJhHmAjciTgfEU3SvwpnEs+o4bF7fqZ0l+37/CCitLoASDuXSHD+HaL1OJblXA/WFDQUgPddF59BE/3DFDe60tzPSGA/TXkjtVqmKS60lr6S0jnzXcrfeEEXoJBSBlAMO2DUMVj4+VO3u5NGJzOyj
  template:
    metadata:
      name: tsl-rag-postgres
      namespace: tsl-rag-prod
