---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tsl-rag-postgres
  namespace: tsl-rag-prod
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAK43z+pvs8CYu0NIIaF4v1B0bSVQDqmjS8sHJ5xJN6R8ni+CxDN9i55bq09sMnIAmJh4RoAN96FlTjf6xfi2iTGw6cQGP4960FGTMMdXvfF6pYEBJ76cFna7nQILIAkmrYWKNAN1zaCPfJr83eeNqDFwhZGzqYXypY1meWWyFfia6wjfIhZYh81S1F+7q6NtoXk+ZzyDQ0ZoTxadwbceUyBXzi3OHxiN/bW1VdW4+YAgAJNBtuIwtq9Nrh6u9NC17UdOdW+BGg/BJFP0qSA8XE/bDnnXS5cp8zHkeRNe41DuCiw8bGh1xg+wBai7rE2MlZd5I7MSBv5Uj9LdN62BCaDy5cw8U1oZWs6Y6L6YWRq4GNBiWXJW50eJpjHUJSpyEez1CfSz9lS5eSk3/agXvXfmpmcdBGDQApOy9ncHKksnAgAcVAxDweeaf5Ni1fJwhxXhgN6SHWHQUDtDSiSfYDaqiynfqLSxcUhGWDA/mskAXOVRk7X9zMGqGynU1SH6O+cUSvusZKAPju9rsClAnTKdoJjWkySfW1HpWSyKK/CO8Sel7Rf7LvTWlwBcP2B53zwwhrp4ZC9z1lQz935k5XsCSTYJMDZXydTDhfzjz8t2YnqGntR7ZLcaUhoI2oBtOqzB/UrlFhswc9h0yWrcuRrUudu8aOnTgKMImEt1vp7Og85Kn1KOs4GFGQC18URpc9H3+ekRy4wnzzMANLsYkue3PvAee4xN+vNJTQODfAdGIzrYuiV7daBJf/feCaFaU=
    POSTGRES_USER: AgAaVXIDOyWv9C662XWaB7vNid+vu0NRJDcEtKJaOtzt4MRBtTJW8mes/wynOIl5Oe7IR2UqZKr4Xw9UhA5mZCHPBITxeopGky/IMUdJMvx44AVGPJPhxjP5XyA8ldOSmWvn6pu63hUFw1Xi/6fYx0xvJWb/hS4ylKnBcP/U2DqLfZHqz4tkcaxw/Ixlq48SGi42sy+93UIswoWUAc84hLJpITYN2xLvyHDTGSbwsSLphnM13MNWExNpwlC2Iygh3oarLL/ZCaSiKp7H+o0lq+ZH1pa9I0/1LDhg5tAlScHvKJ2JKn+KwedjJPRIMY3UqhJC0m+F4YSFkOmfZ8ApVi4Qyrx+wI23VFKbYZZLucmXBej/FZ6d11hDn3LiR0GTQEz3l80uQtItqi+tFqlbY848o3XAVy6HpQgtFoxVvIA9Pab5Nen0y8PTOR6fU5ePr6jtR3ff0ULviCj5hfLK+eR2MpPXwxbZ437bFx12uPHzbxwdSRTYiy5FbLDwX4ecXEp8ScoBnwDX8TOI3GpeuCpKXwoXundyAdmpt1+maQu6Mh9wMrymcwNu09qDMSZmMEnTgZv+2Ae/F48pv9mvDYS1zh0frNNoG/9MdPBjfbyTKpVnDfmiXJsHoDhIPOvgILYWrGdEaGgffHj4GWXfDDjLKRDPYL8c6fl6Ww3+pJhsHymYGqnr9ZcBfNavBJQcmMvNdOPHmoNY
  template:
    metadata:
      name: tsl-rag-postgres
      namespace: tsl-rag-prod
