---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tsl-rag-postgres
  namespace: tsl-rag
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAK2/ScHlBnxSpWdAn8gVgWybDxKWLSWnvYL/+RwEMyoPTqm8EmMliKIfY3SoMPhulqaNlv/rbhEIEBPq2/6gcgDc7l8VEvjxBOXag6a6XLWvjUEji/9awW75qrrRmbuAq5i83maI5i9/NUYnvzzrrJfrNHYHAFFs8TrBa1F7Mouat9FufLCIucveSwv/EHGg2XqGF+eKvUes9DRolBbYjxIzd5UOoRk0jQ3argVA4rFKMLXyaIHAxhggXAEHwZkn0q+2kbq9Rsz1hn5ARfXunBzlYQCttuv5uq+1DnwIA8ZbBqeOMvd+xOooCS8WWePHFBucVQrQ6MqWgrkdLL7SVxn9Hsi42u+tn6oY9ca9DuSve+0LTiA0zNKmlr5LP+3TOmtfEAH3UG8zts8MZhZ7aIVhO2zMhI6aMW+rLGQyKJXWmAm135onxZGppjNmMAqVxiC9rlTJXza/AJ71zXxVFVZw1WfBAgCnTPDLEjMFykOHG6g61f8GINDTwLSAgnchX7c0y/D0HvntSlq7Q4t2lIVtV1p0ldPNRXQDucPJisOYesxOOJ9pKtxw9u9inFXUSNRaI4ghsV5vfFNMSD+9Z3O0Fg/weQlLki8/ylEod3jbCvF1lo7pvhyVlfBZlt3z1EOmCJ577fg/8X/lfXFLUJlnlLcuHP9YZX+dcJPYBV9rhFoI8uNdmXgb78T8LhzVfF5Lh4KUa4xxhtaMdjWavFl+576qpkPRkJ5aEYpOrDrg==
    POSTGRES_USER: AgCCmNTObdWgHVZT8nbjG0L52VP1bC6CAHaTMAxTHOkpqqrtHQgZa/MyIJY8ODMU5gqWM+RR8Gy2bfJh3umvnabxyA7qFHpSUjYQ2JzlX57uCzFF1vIy/IadFzLHxjTvNPCrbJSf8cm71tuudLyOCHjyLjQwbjyebHAyif9bHY9JY1MPSATfAj6HQFGZ6GEeECT6Lz2aM1pvU/sk29xWL4mvyVvaHVZuBNaLwmIG8VSAC5JSUeBPEZLMF5AQqXhUVNrfp5rCTHGWJZp8Zv6i8jBEkJnqOTbpmxT7XDENtcGcyKQj/f9ltFuf8vsEhjHu6RyZaQoenGnuwdIGOsdbB42xXQXIue+xpeS7BSsiGF1XwnxL5h48cZ3fcjJ+mJvkIufoHExYe0v4tGYOVANFUJmXxixqnVzrhCX2ewuv5UM4NjD/0WKj+b+nuf1E+vsMJxWGZSjVXay3gYmti+yIJxkTiGtRelx2GEF9kDJlr+G1sIX/2w6u6bYJnzlvZv9TgcUDNkjr4OmECFVIQ71RlTReeDf80UOALls2wixPyLE2LDEaC5tcK7wDBAQdHci+s5zHtRxuEQFovHuum9cqytGHQmwg31H2B9qgBf8RYUUASdEHaW26PindUvwA0bgKrXJZrtS+STOQK1UqPimyvvO4zyVkw9hMfwOiD83ralk3Ji7JlHSwgOZawWVj1HmSyFn/k3pIRmkgWw==
  template:
    metadata:
      name: tsl-rag-postgres
      namespace: tsl-rag
