---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tsl-rag-postgres
  namespace: tsl-rag-staging
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgA1a0doGjZF9AW93FwiVxsoP8HjuqU0SuBlUl9m0gZsMCtBaSPGMKxOE2pcWdrHphBhLY/KMRaPkhjwfjDacUfOgOR/1UF+UFinznQAW7LmnujN2ij/O+q41wJ4KXfwBSJ2IWqDDjUnF6yq4n0e27d+8mxgfM1Onrq1hTZMQ4ysAc/fZftMJ8a7kq/JjogkCfREcu/C14Z+XbL003nddSsm88F0AwtETPM9p70L1ajpgIIvc+2U4icNXdx4o5oWBZTALBR58WJCbnXYJFHQp6PkRVktx0AqxUy3dqzRPoMlJgT+SOR4c2PqdJPV6fxVRnIXfKKRILjZya+PwpW16E/xVj+HDSmaBQMjtw8hKJFvp+MH+Qoi+cZpXXDH08Cd6Iz3rwRj7nQIi6+uZKR54r7qtEHEtFL8l1qw4EvABgzkzC8NwbYxGGRjxqmfl4zZc07/Uu7bUNy1WM4Q8oeHxFyLrzdggFIIlM6xQak2nYeL3hUygdBx0z2C+PfKijYS7DLy2GhkuzhcaoAh6rjocUi1nfFrYD0bEbEIRjpOa6BWbYPml4Inu1A8AvZsg/7oepm/CpuOKxMXwLrnpngMFlKIYLzEH8hyN1xYfwWt0BbqZg2FsR2Xwhm7xCe3yqXAEnDsDtXVhwkkX4EunWBXkNJdLMmxgz725nnDCCv66b24aP10LBptaGE2LxmlR+85LFwEG3iduPxM5X2MCXF7gIr966C4/lYrLocl4Di9hJxpnB/Z7cTO5uvTjZs9mbZendA=
    POSTGRES_USER: AgAPPw+8Wk5X6R779J6biyIpxH2rzN0BVBTQmsUEkGgEl6ngWaVqpLvw1upQina2O9jsGW8Pyy0ISylooDDqZrjkYJGjlywV2aHFF9MHfJfMq7BGyOlPGnceUtsaKup9V+jxmKgmE7ytTXWwnieATeOnqTWNOq+xJWzkz56C398ek4p5xnOFHAfsUvNzZ1jVKxTFuiPf21S3HdcC2rDLPE0rVmbisV5h2ydIm7KqIj7vZpgKvvVq1CIGOe9JDC3n8PxD3oFY1wRZk7c/vW/CCAZZF1zz43dYGmf3uQaLqCp2SIObjGupUijX5w8eq3BiSJIQ2yziCOOmqmY3qsxkX8Hv+rgOYLpbZhMYjKq2qjOa/NdLM7XbiEoP871jfIIEvgbr3EopYFEuR+pIK9mzWkpgYLbb5EPd9tN3JDBYnGGTG3PPwm+DB9WY6WXkYrUcaWn8VjrXR3lSEGnEnkkaISq6TqudT50UwJClwpC81Uplx/3j9zPF+X9sEUPxcHmB/kcbJ8xDlBWhuO3RpBK0NgPoYmKngY+IGy/dAPe6SfwGmcKuUEuXte2fTg8Pi3o9u2mQ6fPfOfnYYbElJZ7+lKAW6fn4vrkI84C5hPihl4LVMJ5DnJtedVhfmgejJXrqT3owJ2Uk9I856ddg0xNhkCTQHrpZhCf8Nui9jVeE/HDY9AB6Pn6s36kx7vV1LOHCzUZY6q8OSGC/
  template:
    metadata:
      name: tsl-rag-postgres
      namespace: tsl-rag-staging
