---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tsl-rag-postgres
  namespace: tsl-rag-staging
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAcuiVX0637P5C1+m0f6Uxy+TsPztGEcaH+AlK161BjrZ4GmN7x1utHIIBbopCAOJj90dQGEt+ra5FyXSkRFGVwxhSZqTkCqCvMHL40ThNozYkQf+byfhp/VzF8zzRYyqJt/uk9xZg/IyNpcVboNMQGtx434QIWZIa5ydr0QWkgiORQrln0Xh0ajuoFASrR7cT/bB2scqgyjLKKJm9I6OUXG9E6ZFbBIWTt5opFL/Bd074wrfTmVGIns4vLZY1zjQrJTaK+/Lpi7ZWYm0RVNPAPgbIrqWDAFqWHjH5NAlar+HDJsjFaAvrxa8LCAd2o2Pl9PQIEkYogPwZqtV7S4T0l0pFaiw9LXLV+udY/KAsOezJs9QNPo8jdVK9E17wkwpfYzhxGdyMxaBCO/TiOXIfNtLTGDUq2BWOSFar74QugUZzi0yiYAkL3hyg1jcnupsR/J/19vsc8A1ltM+GHix3dK3Itw2dHDKTGg28BXAq3V+t7jdYhtsjlKk6PgyzDPTZ6Ts9b5zaYK7AlJbc1ZHjPYjNzX5tfi1GjofRd77VQbh/dKzG6Gc6gfYGygi6x5Uz6EDvkrEdPZMojgrAnHSpl8Y8+KJUsFBs7Epsu/3m7BUS9bLOLuO6SKsxTXbzwnUwvuIYQZN/av2Yw7nOYfTMPcPVPcilvtQwHqqFItmICjYrEnzlbdh7BMVQg31rjcNxUhRPMnb5mXnIdZm7bTOPHLW11j2Lqe3RujZMSe40ejnyv48U61Wbk7nVbaC/9A5Y=
    POSTGRES_USER: AgAJ802Ts+lkDf8Oi99NWmVRkWPrgAy83s6eyQF7/1qSuhTYvLk1xswAzIRh86h0yRI20KVHXNcDyA6nqC7p2DGAzYK5hSNo2X14iDPsutey1f1Xf7TQEq59NA3bOwZ3OPEMZaTH12k8e+sWTfirqX1VNEl501IAjd37dusSkvmHS6i0Zs8mBfcbN1e6ldV350Saovou0czJSC0f9gAEK6SZraJyPpwkTInKMHvwQyMdCE9m9Sdo6Jq7MO0r/LMJEinpLKZQVSKpN6EqUa+WXABjfoRhm8kuGz2qBXuHu2zSFxby3K7pHwVO8NjoOahnZRPlWT7zNXSxhlJwWZXxNrR9S0+GCj2+Vku+P+UCT2sMLnUy2ED2y+6JG1joAZv5T3FP2gcbvi5kiB/W7zj5g8XDe6GQ1eoDjSRs90tPOMvIHW4XxIGAnSdNAaZR7e06NjE6RgDu6m5qUvMfHfAfDE0ZyBXWBo4iElwm0sTDkT76RCYlHepwO7cLvfW9Y6oo+RV2s5M4/7jPQT9bhKBluvuX3y/5SYptBUqEujOAu7aqaMbAKhM+0U2/kx+ouF5wbzG1LXEgEtJgbgLxS1zSBKd0IJtnF4oEzFVb5MhY4THLgvaDqnib6HdBky8E4l0NYZXGAvQVRzFzeMmRmB4SGkYHDwJVlZt1vite7/wYnvwLSg+Zt+Y+mH0mBHojWUjJ4OWd0u9yo9Lw
  template:
    metadata:
      name: tsl-rag-postgres
      namespace: tsl-rag-staging
